### PR TITLE
Automatize Review apps creation process 

### PR DESCRIPTION
**Pull request by leio10**
Use [Github manual triggers](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) to allow us to deploy of a new Review app for a Decidim branch using just a button.

### CODE REVIEW

**Review by agustibr — APPROVED** [review]
LGTM!!! 🚀

**Review by oriolgual — APPROVED** [review]

**Comment by leio10** [comment]
Ok, let's try it!

**Comment by mrcasals** [comment]
Oh wow 😍😍😍😍 How do you trigger it?

**Comment by leio10** [comment]
@mrcasals I'm still working on this on another branch, but it's triggered here: https://github.com/codegram/decidim-staging/actions?query=workflow%3A%22Staging+review+apps+creator%22

**Comment by mrcasals** [comment]
@leio10 so we're triggering it manually? Or do you plan to integrate this with Slack? 😁

**Comment by leio10** [comment]
currently we can do it manually, but these workflows can be triggered with an API call, so it would be very easy to add that part later 😃

**Comment by mrcasals** [comment]
<3

**Pull request merged**
